# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
- task: CmdLine@2
  inputs:
    script: 'docker login -u $(CONTAINER_REGISTRY_USERNAME) -p $(CONTAINER_REGISTRY_PASSWORD) $(CONTAINER_REGISTRY_ADDRESS)' 

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: deployment.template.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/PostProcessingModule/module.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/InferenceModule/module.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/CameraCaptureModule/module.json

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    deploymentid: 'azuredevops-deployment'
    templateFilePath: deployment.template.devops.json
    defaultPlatform: 'arm64v8'
  