# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: qetza.replacetokens.replacetokens-task.replacetokens@3
#   displayName: 'Replace tokens in deployment.template.json'
#   inputs:
#     rootDirectory: EdgeSolution
#     targetFiles: deployment.template.json

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    deploymentid: 'azuredevops-deployment'
    templateFilePath: deployment.template.json
  