# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'jetson nano'

steps:
# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
- task: CmdLine@2
  inputs:
    script: 'docker login -u $(CONTAINER_REGISTRY_USERNAME) -p $(CONTAINER_REGISTRY_PASSWORD) $(CONTAINER_REGISTRY_ADDRESS)' 

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: deployment.template.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/PostProcessingModule/module.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/InferenceModule/module.json

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in deployment.template.json'
  inputs:
    # rootDirectory: EdgeSolution
    targetFiles: modules/CameraCaptureModule/module.json

# - task: AzureIoTEdge@2
#   displayName: 'Azure IoT Edge - Build and Push IoT Edge Solution'
#   inputs:
#     deploymentid: 'azuredevops-deployment'
#     templateFilePath: deployment.template.devops.json
#     defaultPlatform: 'arm64'

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Build module images
  inputs:
    action: Build module images
    templateFilePath: deployment.template.devops.json
    defaultPlatform: arm64  

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Push module images
  inputs:
    action: Push module images
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(AZURE_SUBSCRIPTION)
    azureContainerRegistry: $(CONTAINER_REGISTRY_ADDRESS)
    templateFilePath: deployment.template.devops.json
    defaultPlatform: arm64

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Deploy to IoT Edge devices'
  inputs:
    action: 'Deploy to IoT Edge devices'
    deploymentFilePath: config/deployment.arm64.json
    azureSubscription: wopauliarm
    iothubname: wopaulionnx
    deviceOption: 'Single Device'
    deviceId: edgeDevice
