# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information.

# replace this image with the full path to the ONNX Runtime + OpenVINO base image
FROM mcr.microsoft.com/azureml/onnxruntime:v0.4.0

WORKDIR /app

COPY main.py .

ENTRYPOINT [ "python3", "-u", "./main.py" ]