# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information.

FROM mcr.microsoft.com/azureml/onnxruntime:v0.5.0-tensorrt-l4t-r32.2

WORKDIR /app

COPY main.py .

ENTRYPOINT [ "python3", "-u", "./main.py" ]