# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information.

FROM mcr.microsoft.com/azureml/onnxruntime:latest-openvino-myriad

WORKDIR /app

COPY main.py .

ENTRYPOINT [ "python", "-u", "./main.py" ]