# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information.

FROM manashonnxruntime.azurecr.io/onnxruntime-jetson:v2

WORKDIR /app

COPY main.py .

ENTRYPOINT [ "python3", "-u", "./main.py" ]